###
GET http://localhost:4000/transactions/

###
GET http://localhost:4000/transactions/barChart/

###
GET http://localhost:4000/transactions/sales/

###
GET http://localhost:4000/transactions/pieChart/
###
GET http://localhost:4000/transactions/total/